// Copyright 2026 runbook authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cli

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

func newShellInitCmd() *cobra.Command {
	var shellFlag string

	cmd := &cobra.Command{
		Use:   "shell-init",
		Short: "Output shell integration snippet (source in your profile)",
		Long: `Output a shell snippet that installs runbook integration.

The snippet provides:
  • Tab completion for all commands, flags, and .runbook files
  • alias rb="runbook"
  • runbook-detect — scans the current directory and reports the project environment

Add to your shell profile:

  Bash (~/.bashrc):
    eval "$(runbook shell-init)"

  Zsh (~/.zshrc):
    eval "$(runbook shell-init)"

  Fish (~/.config/fish/config.fish):
    runbook shell-init --shell fish | source`,
		RunE: func(cmd *cobra.Command, args []string) error {
			shell := shellFlag
			if shell == "" {
				shell = detectShell()
			}
			switch shell {
			case "bash":
				return writePosixShellInit(os.Stdout, cmd.Root(), "bash")
			case "zsh":
				return writePosixShellInit(os.Stdout, cmd.Root(), "zsh")
			case "fish":
				return writeFishShellInit(os.Stdout, cmd.Root())
			default:
				return fmt.Errorf("unsupported shell %q; supported shells: bash, zsh, fish", shell)
			}
		},
	}

	cmd.Flags().StringVar(&shellFlag, "shell", "", "target shell (bash, zsh, fish); defaults to $SHELL basename")
	_ = cmd.RegisterFlagCompletionFunc("shell", func(_ *cobra.Command, _ []string, _ string) ([]string, cobra.ShellCompDirective) {
		return []string{"bash", "zsh", "fish"}, cobra.ShellCompDirectiveNoFileComp
	})

	return cmd
}

// detectShell returns the base name of $SHELL (e.g. "bash", "zsh", "fish").
func detectShell() string {
	return filepath.Base(os.Getenv("SHELL"))
}

// shellWriter wraps an io.Writer and accumulates the first write error,
// so callers can chain writes and check the error once at the end.
type shellWriter struct {
	w   io.Writer
	err error
}

func (sw *shellWriter) s(str string) {
	if sw.err == nil {
		_, sw.err = io.WriteString(sw.w, str)
	}
}

func (sw *shellWriter) f(format string, args ...any) {
	if sw.err == nil {
		_, sw.err = fmt.Fprintf(sw.w, format, args...)
	}
}

// writePosixShellInit writes the bash or zsh integration snippet to w.
func writePosixShellInit(w io.Writer, root *cobra.Command, shell string) error {
	var compBuf bytes.Buffer
	switch shell {
	case "bash":
		if err := root.GenBashCompletionV2(&compBuf, true); err != nil {
			return fmt.Errorf("generating completion: %w", err)
		}
	case "zsh":
		if err := root.GenZshCompletion(&compBuf); err != nil {
			return fmt.Errorf("generating completion: %w", err)
		}
	}

	promptVar := "PS1"
	if shell == "zsh" {
		promptVar = "PROMPT"
	}

	sw := &shellWriter{w: w}

	// Header
	sw.f("# ── runbook shell integration (%s) %s\n", shell, divider(50))
	sw.f("# Generated by: runbook shell-init --shell %s\n", shell)
	sw.s("# Source in your profile:  eval \"$(runbook shell-init)\"\n\n")

	// Inlined completion script — no subprocess at shell startup.
	sw.f("# ── Tab completion (inlined) %s\n", divider(52))
	sw.s(compBuf.String())
	sw.s("\n")

	// Alias
	sw.f("# ── Alias %s\n", divider(60))
	sw.s("alias rb=\"runbook\"\n\n")

	// runbook-detect function
	sw.f("# ── runbook-detect: project environment summary %s\n", divider(33))
	sw.s(posixDetectFunc)
	sw.s("\n")

	// Prompt indicator + optional integration
	sw.f("# ── Prompt integration (optional) %s\n", divider(46))
	sw.s(posixPromptIndicatorFunc)
	sw.f("# Uncomment to prepend a runbook indicator to your %s:\n", promptVar)
	sw.f("# export %s='$(runbook-prompt-indicator)'\"%s\"\n\n", promptVar, "$"+promptVar)

	return sw.err
}

// writeFishShellInit writes the fish integration snippet to w.
func writeFishShellInit(w io.Writer, root *cobra.Command) error {
	var compBuf bytes.Buffer
	if err := root.GenFishCompletion(&compBuf, true); err != nil {
		return fmt.Errorf("generating completion: %w", err)
	}

	sw := &shellWriter{w: w}

	// Header
	sw.s("# ── runbook shell integration (fish) " + divider(43) + "\n")
	sw.s("# Generated by: runbook shell-init --shell fish\n")
	sw.s("# Source in ~/.config/fish/config.fish:\n")
	sw.s("#   runbook shell-init --shell fish | source\n\n")

	// Inlined completion script
	sw.s("# ── Tab completion (inlined) " + divider(52) + "\n")
	sw.s(compBuf.String())
	sw.s("\n")

	// Alias (fish uses abbr for interactive abbreviations)
	sw.s("# ── Alias " + divider(60) + "\n")
	sw.s("abbr --add rb runbook\n\n")

	// runbook-detect function
	sw.s("# ── runbook-detect: project environment summary " + divider(33) + "\n")
	sw.s(fishDetectFunc)
	sw.s("\n")

	// Prompt indicator + optional integration
	sw.s("# ── Prompt integration (optional) " + divider(46) + "\n")
	sw.s(fishPromptIndicatorFunc)
	sw.s("# Uncomment to prepend a runbook indicator to your fish prompt:\n")
	sw.s("# functions --copy fish_prompt __runbook_orig_fish_prompt 2>/dev/null\n")
	sw.s("# if not functions --query __runbook_orig_fish_prompt\n")
	sw.s("#   function __runbook_orig_fish_prompt; end\n")
	sw.s("# end\n")
	sw.s("# function fish_prompt\n")
	sw.s("#   echo -n (runbook-prompt-indicator)\n")
	sw.s("#   __runbook_orig_fish_prompt\n")
	sw.s("# end\n\n")

	return sw.err
}

// divider returns a string of "─" characters of length n.
func divider(n int) string {
	b := make([]byte, 0, n*3) // ─ is 3 bytes in UTF-8
	for range n {
		b = append(b, "─"...)
	}
	return string(b)
}

// ─────────────────────────────────────────────────────────────────────────────
// Embedded shell functions
// ─────────────────────────────────────────────────────────────────────────────

// posixDetectFunc is the runbook-detect shell function for bash and zsh.
// Variable names use a short _rb_ prefix to avoid collisions with user env.
// Process substitution (<(...)) is used for line-by-line awk output; this
// requires bash or zsh and will not work in plain /bin/sh.
const posixDetectFunc = `runbook-detect() {
  local _d="${1:-.}"
  local _type="unknown" _tools="" _name
  local _count=0 _names="" _envs="" _rbtools="" _all="" _stat=""
  local _f _e _t

  # ── Project type detection ───────────────────────────────────────────────
  if   [ -f "$_d/go.mod" ]; then
    _type="Go project"; _tools="go golangci-lint"
  elif [ -f "$_d/package.json" ]; then
    _type="Node.js project"
    if   [ -f "$_d/pnpm-lock.yaml" ]; then _tools="node pnpm"
    elif [ -f "$_d/yarn.lock" ];       then _tools="node yarn"
    else                                    _tools="node npm"
    fi
  elif [ -f "$_d/Cargo.toml" ]; then
    _type="Rust project"; _tools="cargo rustc"
  elif [ -f "$_d/pyproject.toml" ] || [ -f "$_d/requirements.txt" ]; then
    _type="Python project"; _tools="python3 pip"
  elif [ -f "$_d/Dockerfile" ]; then
    _type="Docker project"; _tools="docker"
  elif [ -f "$_d/docker-compose.yml" ] || [ -f "$_d/docker-compose.yaml" ]; then
    _type="Docker Compose"; _tools="docker"
  elif [ -f "$_d/Makefile" ]; then
    _type="Make-based build"; _tools="make"
  elif ls "$_d"/*.tf >/dev/null 2>&1; then
    _type="Terraform project"; _tools="terraform"
  elif [ -d "$_d/kubernetes" ] || [ -d "$_d/k8s" ]; then
    _type="Kubernetes project"; _tools="kubectl helm"
  elif [ -d "$_d/.github/workflows" ]; then
    _type="GitHub Actions CI"; _tools="gh"
  elif [ -f "$_d/Jenkinsfile" ]; then
    _type="Jenkins CI"
  fi

  _name=$(basename "$(cd "$_d" && pwd)")

  # ── Scan .runbook files, extract environments and required tools ──────────
  if ls "$_d"/*.runbook >/dev/null 2>&1; then
    for _f in "$_d"/*.runbook; do
      _count=$((_count + 1))
      _names="${_names:+$_names, }$(basename "$_f")"

      while IFS= read -r _e; do
        [ -z "$_e" ] && continue
        case " $_envs " in
          *" $_e "*) ;;
          *) _envs="${_envs:+$_envs, }$_e" ;;
        esac
      done < <(awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f&&/^environments:/{if(/\[/){s=$0;sub(/^environments:[[:space:]]*\[[[:space:]]*/,"",s);sub(/[[:space:]]*\].*/,"",s);n=split(s,a,/,[[:space:]]*/);for(i=1;i<=n;i++)if(length(a[i]))print a[i]}else{e=1};next} e&&/^  - /{print substr($0,5);next} e&&/^[^[:blank:]]/{e=0}' "$_f" 2>/dev/null)

      while IFS= read -r _t; do
        [ -z "$_t" ] && continue
        case " $_rbtools " in
          *" $_t "*) ;;
          *) _rbtools="${_rbtools:+$_rbtools }$_t" ;;
        esac
      done < <(awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f&&/^requires:/{r=1;next} r&&/^  tools:/{if(/\[/){s=$0;sub(/^  tools:[[:space:]]*\[[[:space:]]*/,"",s);sub(/[[:space:]]*\].*/,"",s);n=split(s,a,/,[[:space:]]*/);for(i=1;i<=n;i++)if(length(a[i]))print a[i]}else{t=1};r=0;next} r&&/^[^[:blank:]]/{r=0} t&&/^    - /{print substr($0,7);next} t&&/^[^[:blank:]]/{t=0}' "$_f" 2>/dev/null)
    done
  fi

  # ── Merge project tools + runbook-required tools, deduplicate ────────────
  for _t in $_tools $_rbtools; do
    [ -z "$_t" ] && continue
    case " $_all " in
      *" $_t "*) ;;
      *) _all="${_all:+$_all }$_t" ;;
    esac
  done

  # ── Check each tool with command -v ──────────────────────────────────────
  for _t in $_all; do
    [ -z "$_t" ] && continue
    if command -v "$_t" >/dev/null 2>&1; then
      _stat="${_stat:+$_stat, }$_t ✓"
    else
      _stat="${_stat:+$_stat, }$_t ✗"
    fi
  done

  # ── Output summary ───────────────────────────────────────────────────────
  printf '📂 Project: %s (%s)\n' "$_name" "$_type"
  if [ "$_count" -gt 0 ]; then
    printf '📋 Runbooks: %d found (%s)\n' "$_count" "$_names"
  else
    printf '📋 Runbooks: none found\n'
  fi
  [ -n "$_stat" ] && printf '🔧 Tools: %s\n' "$_stat"
  [ -n "$_envs" ] && printf '🌍 Environments: %s\n' "$_envs"
  return 0
}
`

// posixPromptIndicatorFunc is the runbook-prompt-indicator function for bash/zsh.
// It is intentionally minimal: a fast glob count with no parsing.
const posixPromptIndicatorFunc = `runbook-prompt-indicator() {
  local _n=0 _f
  for _f in *.runbook; do [ -f "$_f" ] && _n=$((_n + 1)); done
  [ "$_n" -gt 0 ] && printf '[rb:%d] ' "$_n"
}
`

// fishDetectFunc is the runbook-detect function for fish shell.
const fishDetectFunc = `function runbook-detect
    set -l _d .
    test (count $argv) -gt 0; and set _d $argv[1]

    set -l _type "unknown"
    set -l _tools

    # ── Project type detection ─────────────────────────────────────────────
    if test -f $_d/go.mod
        set _type "Go project"; set _tools go golangci-lint
    else if test -f $_d/package.json
        set _type "Node.js project"
        if test -f $_d/pnpm-lock.yaml;   set _tools node pnpm
        else if test -f $_d/yarn.lock;   set _tools node yarn
        else;                            set _tools node npm
        end
    else if test -f $_d/Cargo.toml
        set _type "Rust project"; set _tools cargo rustc
    else if test -f $_d/pyproject.toml; or test -f $_d/requirements.txt
        set _type "Python project"; set _tools python3 pip
    else if test -f $_d/Dockerfile
        set _type "Docker project"; set _tools docker
    else if test -f $_d/docker-compose.yml; or test -f $_d/docker-compose.yaml
        set _type "Docker Compose"; set _tools docker
    else if test -f $_d/Makefile
        set _type "Make-based build"; set _tools make
    else if test -n (find $_d -maxdepth 1 -name '*.tf' -print -quit 2>/dev/null)
        set _type "Terraform project"; set _tools terraform
    else if test -d $_d/kubernetes; or test -d $_d/k8s
        set _type "Kubernetes project"; set _tools kubectl helm
    else if test -d $_d/.github/workflows
        set _type "GitHub Actions CI"; set _tools gh
    else if test -f $_d/Jenkinsfile
        set _type "Jenkins CI"
    end

    set -l _name
    if test "$_d" = .
        set _name (basename (pwd))
    else
        set _name (basename $_d)
    end

    # ── Scan .runbook files ────────────────────────────────────────────────
    set -l _count 0
    set -l _names
    set -l _envs
    set -l _rbtools

    for _f in $_d/*.runbook
        test -f $_f; or continue
        set _count (math $_count + 1)
        set -a _names (basename $_f)

        for _e in (awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f&&/^environments:/{if(/\[/){s=$0;sub(/^environments:[[:space:]]*\[[[:space:]]*/,"",s);sub(/[[:space:]]*\].*/,"",s);n=split(s,a,/,[[:space:]]*/);for(i=1;i<=n;i++)if(length(a[i]))print a[i]}else{e=1};next} e&&/^  - /{print substr($0,5);next} e&&/^[^[:blank:]]/{e=0}' $_f 2>/dev/null)
            contains -- $_e $_envs; or set -a _envs $_e
        end

        for _t in (awk 'NR==1&&/^---/{f=1;next} f&&/^---/{exit} f&&/^requires:/{r=1;next} r&&/^  tools:/{if(/\[/){s=$0;sub(/^  tools:[[:space:]]*\[[[:space:]]*/,"",s);sub(/[[:space:]]*\].*/,"",s);n=split(s,a,/,[[:space:]]*/);for(i=1;i<=n;i++)if(length(a[i]))print a[i]}else{t=1};r=0;next} r&&/^[^[:blank:]]/{r=0} t&&/^    - /{print substr($0,7);next} t&&/^[^[:blank:]]/{t=0}' $_f 2>/dev/null)
            contains -- $_t $_rbtools; or set -a _rbtools $_t
        end
    end

    # ── Merge and deduplicate tools ────────────────────────────────────────
    set -l _all $_tools
    for _t in $_rbtools
        contains -- $_t $_all; or set -a _all $_t
    end

    # ── Check each tool with type -q ──────────────────────────────────────
    set -l _parts
    for _t in $_all
        if type -q $_t
            set -a _parts "$_t ✓"
        else
            set -a _parts "$_t ✗"
        end
    end

    # ── Output summary ─────────────────────────────────────────────────────
    echo "📂 Project: $_name ($_type)"
    if test $_count -gt 0
        echo "📋 Runbooks: $_count found "(string join ', ' $_names)
    else
        echo "📋 Runbooks: none found"
    end
    test (count $_parts) -gt 0; and echo "🔧 Tools: "(string join ', ' $_parts)
    test (count $_envs)  -gt 0; and echo "🌍 Environments: "(string join ', ' $_envs)
    return 0
end
`

// fishPromptIndicatorFunc is the runbook-prompt-indicator function for fish.
// Fast: glob count only, no file parsing.
const fishPromptIndicatorFunc = `function runbook-prompt-indicator
    set -l _files (ls -1 *.runbook 2>/dev/null)
    set -l _n (count $_files)
    test $_n -gt 0; and echo -n "[rb:$_n] "
end
`
