# typed: false
# frozen_string_literal: true

# This formula is auto-generated by GoReleaser during releases.
# Manual edits will be overwritten. To install from the tap:
#
#   brew install runbookdev/tap/runbook
#
# For development builds from source:
#
#   brew install --HEAD runbookdev/tap/runbook
#
class Runbook < Formula
  desc "Executable runbooks as code — documentation and automation in a single file format"
  homepage "https://github.com/runbookdev/runbook"
  license "Apache-2.0"
  head "https://github.com/runbookdev/runbook.git", branch: "main"

  # GoReleaser replaces this block during release.
  # --- BEGIN GORELEASER ---
  version "0.0.0-dev"
  # on_macos do
  #   on_arm do
  #     url "https://github.com/runbookdev/runbook/releases/download/v#{version}/runbook_#{version}_darwin_arm64.tar.gz"
  #     sha256 "PLACEHOLDER"
  #   end
  #   on_intel do
  #     url "https://github.com/runbookdev/runbook/releases/download/v#{version}/runbook_#{version}_darwin_amd64.tar.gz"
  #     sha256 "PLACEHOLDER"
  #   end
  # end
  # on_linux do
  #   on_arm do
  #     url "https://github.com/runbookdev/runbook/releases/download/v#{version}/runbook_#{version}_linux_arm64.tar.gz"
  #     sha256 "PLACEHOLDER"
  #   end
  #   on_intel do
  #     url "https://github.com/runbookdev/runbook/releases/download/v#{version}/runbook_#{version}_linux_amd64.tar.gz"
  #     sha256 "PLACEHOLDER"
  #   end
  # end
  # --- END GORELEASER ---

  depends_on "go" => :build
  depends_on "sqlite" => :optional

  def install
    ldflags = %W[
      -s -w
      -X main.version=#{version}
      -X main.commit=#{Utils.git_short_head}
      -X main.date=#{time.iso8601}
    ]
    system "go", "build", *std_go_args(ldflags:), "./cmd/runbook"
    prefix.install Dir["templates"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/runbook version")
    assert_match "VALID", shell_output("#{bin}/runbook validate #{prefix}/templates/deploy.runbook 2>&1")
  end
end
